#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --output DP-4 --output HDMI-0 --same-as DP-2

bspc monitor DP-2 -d 1 2 3
bspc monitor DP-4 -d 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

image=$(cut -d\' -f 2 -s $HOME/.fehbg)

~/.config/polybar/launch.sh
~/.fehbg &
wal -i $image -n &
picom --xrender-sync-fence --experimental-backend &
wmname LG3D  # Fix Java apps
setxkbmap -model pc104 -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle
xautolock -locker "i3lock-fancy-dualmonitor" -time 3 -corners "+00-" -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" -cornerdelay 30 -cornerredelay 30 &
xsetroot -cursor_name left_ptr &  # Change cursor in bspwm
killall -9 -q redshift 
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}') -P &
