#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3
bspc monitor DP-4 -d 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/polybar/launch.sh &
~/.fehbg &
compton &
wmname LG3D  # Fix Java apps
setxkbmap -model pc104 -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle
xautolock -locker "i3lock-fancy-dualmonitor" -time 5 -corners "+00-" &
xsetroot -cursor_name left_ptr &  # Change cursor in bspwm
