#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

killall -q polybar
compton &
polybar main &
polybar second &
~/.fehbg &
wmname LG3D
setxkbmap -model pc104 -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle
